platform :ios, '9.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EMiOSVideoCallDemo' do

    pod 'Masonry'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'SDWebImage', '~> 3.7.2'
    #pod 'Hyphenate'

end
